// src/react/ProductPage/Product.tsx
import { Component, type ReactNode } from "react"
import { type Product } from "@/types/product"
import { fetchProductById } from "@/libs/hygraph"
import formatCurreny from "@/utils/currency"
import WspButton from "./WspButton"
import StockBadge from "./StockBadge"
import ImageSlider from "./ImageSlider"

interface IProps {
  productID: string | undefined
  productURL: string
}
interface IState {
  product: Product | undefined
  loading: boolean
  error: string
}

export default class ProductPage extends Component<IProps, IState> {
  constructor(props: IProps) {
    super(props)
    this.state = {
      product: undefined,
      loading: false,
      error: "",
    }
  }

  componentDidMount(): void {
    this.setState((prevState) => ({ ...prevState, loading: true }))
    const { productID } = this.props
    if (!productID) {
      return this.setState((prevState) => ({
        ...prevState,
        error: "Producto No encontrado o ha sido eliminado.",
      }))
    }

    fetchProductById(productID)
      .then(({ producto }) => {
        this.setState((prevState) => ({
          ...prevState,
          product: producto,
          loading: false,
        }))
      })
      .catch(() => {
        this.setState((prevState) => ({
          ...prevState,
          error: "Error al comunicarse con el servidor, por favor intentar más tarde.",
        }))
      })
  }

  render(): ReactNode {
    const { product, error, loading } = this.state

    if (error) return <div>{error}</div>
    if (loading) return <div>cargando...</div>
    if (!product) return <div>Producto No encontrado o ha sido eliminado.</div>

    const { productURL } = this.props
    const { stock, title, description, tag, size, price } = product
    const hrefWsp = `https://api.whatsapp.com/send?phone=59896667633&text=Quiero este producto: ${productURL}`
    return (
      <div>
        <div className="grid md:grid-cols-3 grid-cols-1">
          <ImageSlider product={product!} />
          <div className="md:p-12 px-6 mb-12 md:mb-0 md:order-last order-first">
            <h2>{title}</h2>
            <h3>{tag}</h3>
            <p>{description}</p>
            <p>Talla: {size}</p>
            <p>Precio: {formatCurreny(price)}</p>
            <StockBadge stock={stock} />
            <WspButton href={hrefWsp} />
          </div>
        </div>
      </div>
    )
  }
}

// src/svelte/Product.svelte
<script lang="ts">
  import Typographi from './components/Typographi.svelte'
  import WspButton from './components/WspButton.svelte'
  import StockBadge from './components/StockBadge.svelte'
  import { formatCurreny } from '@/utils/currency'
  import { fetchProudctById } from '../libs/graphql'
  import ProductSlider from './components/ProductSlider.svelte'

  interface Params {
    id: string
  }

  export let params = {} as Params
  const { id } = params

  const productURL = window.location.href
  const hrefWsp = `https://api.whatsapp.com/send?phone=59896667633&text=Quiero este producto: ${productURL}`
</script>

<div class="dark:bg-dark-primary py-12">
  {#await fetchProudctById(id)}
    <Typographi as={'p'} variant={'BODY'} color={'BLACK'} darkColor={'WHITE'}>cargando...</Typographi>
  {:then product}
    {#if !product}
      <Typographi as={'p'} variant={'BODY'} color={'BLACK'} darkColor={'WHITE'}>Producto no encontrado</Typographi>
    {:else}
      <section class="max-w-6xl mx-auto">
        <div class="grid sm:grid-cols-10">
          <div class="sm:col-span-5">
            <ProductSlider images={product.images} />
          </div>
  
          <div class="sm:col-span-5">
            <Typographi as={'h2'} variant={'TITLE'} color={'ACCENT_AMATISTA'}>{product.title}</Typographi>
            <Typographi as={'h3'} variant={'SUBTITLE'} color={'BLACK'} darkColor={'WHITE'} className={'mb-4'}>{formatCurreny(product.price)}</Typographi>
            {#each product.categories as category}
              <Typographi as={'h3'} variant={'SUBTITLE'} color={'BLACK'} darkColor={'WHITE'}>{category}</Typographi>
            {/each}

            <StockBadge isInStock={product.isInStock}/>
            <Typographi as={'p'} variant={'BODY'} color={'BLACK'} darkColor={'WHITE'}>{@html product.description}</Typographi>
            {#if product.stockQuantity > 0}
              <Typographi as={'p'} variant={'BODY'} color={'BLACK'} darkColor={'WHITE'}>Unidades disponibles: {product.stockQuantity}</Typographi>
            {/if}

            <div>
              <WspButton href={hrefWsp}/>
            </div>
          </div>
        </div>
      </section>
    {/if}
  {:catch}
    <p>Server not available</p>
  {/await}
</div>
