// src/svelte/components/ProductCard.svelte
<script lang="ts">
  import { link } from 'svelte-spa-router'
  import type { Product } from '../../types/product'

  export let product: Product

  const { id, title, price, stock } = product
  const { url: src, width, height } = product.thumbnail
</script>

<li
  class="p-6 transition-colors duration-300 border-2 border-transparent hover:border-white group"
>
  <a
    href="/{id}"
    use:link
  >
    <div
      class="w-full h-auto mb-2 overflow-hidden aspect-square"
    >
      <img
        {src}
        {width}
        {height}
        alt={id}
        class="object-center w-auto h-full mx-auto transition-transform duration-500 group-hover:scale-105"
      />
    </div>
    <h3>{title}</h3>
    <p>{price}</p>
    <p>{stock}</p>
  </a>
</li>

// src/react/ShopPage/ProductCard.tsx
import { Component, type ReactNode } from "react"
import { type Product } from "@/types/api"
import formatCurency from "@/utils/currency"
import { fetchProductById } from "@/libs/hygraph"

interface IProps {
  product: Product
}

export class ProductCard extends Component<IProps> {
  handleMouseEnter = () => {
    const { id } = this.props.product
    fetchProductById(id)
  }

  render(): ReactNode {
    const { id, title, price, miniatura, stock } = this.props.product

    const href = `/tienda/${id}`
    const priceFormatted = formatCurency(price)
    const isSoldout = stock < 1 || !stock
    return (
      <a
        href={href}
        className="inline-block group"
        onMouseEnter={this.handleMouseEnter}
      >
        <div className="relative mb-4 overflow-hidden">
          <img
            src={miniatura.url}
            alt={title}
            className="duration-1000 group-hover:scale-110 w-full aspect-portrait object-cover object-center"
          />
          {isSoldout && (
            <span className="absolute px-3 py-1 text-sm rounded-full bottom-3 left-3 text-raw_white bg-midnight_green-900">
              Agotado
            </span>
          )}
        </div>
        <h3 className="mb-2 font-semibold dark:text-white">{title}</h3>
        <p className="dark:text-white">{priceFormatted}</p>
      </a>
    )
  }
}
